### ISSUE TITLE
Ali Reza : React

### ISSUE THREAD

**Issue by alisamadiii** [asakatsuOrg/AsaKatsuProject#10]
**What is your goal?**
To learn React

### Steps to achieve the goal (not required)
  - [x] Learn Class Component & Function
  - [x] Learn useState & useEffect
  - [x] Learn GSAP animation
  - [ ] Routing
  - [ ] Firebase
  - [ ] Projects
  - [ ] VITE

**Do you have a target date for this? If yes, write below**
January 16, 2023

**What will you achieve by completing this goal?**
I'll become a _React Developer_

**Additional context**
With the help of God, I can do it.

**Comment by avie-dev** [comment]
@AliReza1083 Is this done?

**Comment by alisamadiii** [comment]
@avie-dev 
Everything was done Avie I think.
I set my goals, my exercise time table.

**Comment by alisamadiii** [comment]
Sorry @avie-dev for closing this issue too late.
