### ISSUE TITLE
Add CONTRIBUTION CODE OF CONDUCT

### ISSUE THREAD

**Issue by Kellsonphilips** [asakatsuOrg/AsaKatsuProject#11]
I think we will need contribution code of conduct to guide everyone.

**Comment by alisamadiii** [comment]
@Kellsonphilips 
what is _contribution code of conduct_ Philips?

**Comment by Kellsonphilips** [comment]
Code of conduct is a guideline of manners that are tolerated amongst everyone who wishes to contribute or participate in this project. This is to avoid conflicts, hope this explanation is clear enough.

**Comment by avie-dev** [comment]
@Kellsonphilips I see. Thank you! I totally forgot about that. Adding it now.

**Comment by Kellsonphilips** [comment]
That's right.

**Comment by avie-dev** [comment]
@Kellsonphilips I added one, so please check, and if okay, close this issue. Thank you!

**Comment by Kellsonphilips** [comment]
That's perfect
