### ISSUE TITLE
Set Goal (Avie): Draw illustration for animation 

### ISSUE THREAD

**Issue by avie-dev** [asakatsuOrg/AsaKatsuProject#124]
**What is your goal?**
Draw illustration for animation, 6 poses

### Steps to achieve the goal (not required)
  - [ ] Think of a concept
  - [ ] Pose 1
  - [ ] Pose 2 
  - [ ] Pose 3 
  - [ ] Pose 4 
  - [ ] Pose 5 
  - [ ] Pose 6

**Do you have a target date for this? If yes, write below**
- 
**What will you achieve by completing this goal?**
- 
**Additional context**
-

**Comment by Kellsonphilips** [comment]
can't wait to see this masterpiece in themaking.

**Comment by alisamadiii** [comment]
Looking forward to see it 🚀✌️

**Comment by avie-dev** [comment]
Haha wait I’m still working on it🤣

**Comment by Kellsonphilips** [comment]
😂😂

**Comment by alisamadiii** [comment]
OK

**Comment by Kellsonphilips** [comment]
where is the illustration preview @avie-dev
