### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by alisamadiii** [asakatsuOrg/AsaKatsuProject#133]
why not make a website for this Repo?

**Comment by Kellsonphilips** [comment]
That seems like a good idea but do you have a mockup or something?

**Comment by alisamadiii** [comment]
I'll make one.

**Comment by alisamadiii** [comment]
Should I continue making it?

https://user-images.githubusercontent.com/99729607/196105642-f9a12395-d5d3-4832-8a94-3ed0ec2a4f54.mp4

**Comment by Kellsonphilips** [comment]
Looks good and can be better. continue @AliReza1083

**Comment by Kellsonphilips** [comment]
Create the skeleton and we make it open source and everyone will contribute to make it better

**Comment by alisamadiii** [comment]
Sorry @Kellsonphilips,
what do you mean Skeleton?

**Comment by Kellsonphilips** [comment]
I mean the UI and how it can be structured at the beginner stage. That is the skeleton.

**Comment by alisamadiii** [comment]
I've made a repo for this project...
I've connected to Netlify...
You can see the website live...
https://github.com/AliReza1083/Asakatsu

**Comment by alisamadiii** [comment]
@Kellsonphilips

**Comment by alisamadiii** [comment]
I am making the website like this that the user must add their data in json file and do nothing.
the website will automatically will do them.

**Comment by avie-dev** [comment]
Ali! Fire this✨ thank you!
Actually Nate wanted to do the same, but you can collaborate✨💪

**Comment by alisamadiii** [comment]
The project is almost done.
Can you make a PR to see if it is working fine or not?
You can add more than one goal by making an object...
Please use the value that I used for mine otherwise you'll get errors...

Repo: https://github.com/AliReza1083/Asakatsu

File location:
`Profile.json`

I'll check the PR tomorrow if there was any.

@avie-dev @Kellsonphilips 

>**Note**
> Check on big screens first, It is not ready for small screens

![image](https://user-images.githubusercontent.com/99729607/196179107-ec5a8eab-1b4a-43e8-8f10-6690d28ddbb6.png)

**Comment by Kellsonphilips** [comment]
It's looking great @AliReza1083 go on with the nav-bar

**Comment by alisamadiii** [comment]
I sent you an image of the data above.
If your goal is completed then set the value to true and The items will be green, if not then the item will remain as white.
![image](https://user-images.githubusercontent.com/99729607/196318269-08b9fab2-ff02-411c-a085-f51eb779e72a.png)

**Comment by alisamadiii** [comment]
The website is done. it is ready.
maybe later I'll add new things onto it.

**Comment by alisamadiii** [comment]
PLEASE make a PR and add your goals, same as I did.
just for checking...
make sure to not use any other words...

**Comment by Kellsonphilips** [comment]
That looks amazing @AliReza1083 thanks for this work. 👏🏼

**Comment by avie-dev** [comment]
@AliReza1083 Nice nice! 
@Kellsonphilips Philips, I haven't heard any word from you about this though..... Although it's open source.. for the new features aside from the progress, I want to be the one checking it... for starters

**Comment by Kellsonphilips** [comment]
@avie-dev Check the discussion section, we are organizing the site and you check it and let us know what you think. 
The link to the live website is also in the discussion. 
After we can know how to implement it with the main project

**Comment by Kellsonphilips** [comment]
The Website discussion https://github.com/asakatsuOrg/AsaKatsuProject/discussions/151

**Comment by AliReza1083** [comment]
> The Website discussion #151

You'll get what we did in the discussion.

**Comment by Kellsonphilips** [comment]
Completed and we need to start maintaining it from Asakatsu website repo
