### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by alisamadiii** [asakatsuOrg/AsaKatsuProject#139]
We have to make a logo for this project.

**Comment by Kellsonphilips** [comment]
That's another good issue @AliReza1083

**Comment by avie-dev** [comment]
Yes! We need a logo! I like this!
Now we need a designer🥹

**Comment by Kellsonphilips** [comment]
I hope that we get a designer as well.

**Comment by alisamadiii** [comment]
I'll make one.

**Comment by Kellsonphilips** [comment]
Do you design also @AliReza1083 ?

**Comment by alisamadiii** [comment]
Yeah hhh

**Comment by Kellsonphilips** [comment]
Too much Talent haha 😆

**Comment by alisamadiii** [comment]
hahaha All thanks to God ✌️

**Comment by Kellsonphilips** [comment]
Maybe we should do pair collaboration so I can learn how to design from you

**Comment by alisamadiii** [comment]
That sounds awesome, let's do it.
I'll learn new things from you as well.

**Comment by alisamadiii** [comment]
How is it? 
![image](https://user-images.githubusercontent.com/99729607/196379581-c7e47c8f-14ba-48db-94a2-73f111e66e7f.png)

**Comment by Kellsonphilips** [comment]
How did you think about that haha. Looks amazing

**Comment by alisamadiii** [comment]
I don't know how hhhh
But My brain and my hands will do the work. 😅😅😅

**Comment by Kellsonphilips** [comment]
@avie-dev what do you think of this logo for AsakatsuOrg and website?

**Comment by Kellsonphilips** [comment]
That's amazing. I want to design my personal logo in 3D

**Comment by alisamadiii** [comment]
This image also has meaning, you have to think about it...😅😅✌️😆
I am not kidding hhh

**Comment by alisamadiii** [comment]
> That's amazing. I want to design my personal logo in 3D

Nice

**Comment by Kellsonphilips** [comment]
But I don't know design haha 😂

**Comment by alisamadiii** [comment]
The meaning -------
`You have to climb the mountain in order to see the sun`
that seems to be amazing...

> This image also has meaning, you have to think about it...😅😅✌️😆 I am not kidding hhh

**Comment by alisamadiii** [comment]
> But I don't know design haha 😂

You'll learn it, it is not a big deal.

**Comment by Kellsonphilips** [comment]
> The meaning -------
> 
> `You have to climb the mountain in order to see the sun`
> 
> that seems to be amazing...
> 
> 
> 
It is amazing 👏👏😍

**Comment by avie-dev** [comment]
@AliReza1083 Amazing!
I see an egg, a mountain, sun..
Can you make the edges a bit softer though?

**Comment by avie-dev** [comment]
> `You have to climb the mountain in order to see the sun`

I love this!!!!

**Comment by avie-dev** [comment]
Ali!!!!! Fireeee!!!

**Comment by alisamadiii** [comment]
> @AliReza1083 Amazing! I see an egg, a mountain, sun.. Can you make the edges a bit softer though?

Yeah I did that.

**Comment by alisamadiii** [comment]
Done!!!
![Logo](https://user-images.githubusercontent.com/99729607/196630565-b9168dae-acb2-4a38-a3d0-2d85c683f363.png)

**Comment by alisamadiii** [comment]
Let me put it as a favicon for the website

**Comment by Kellsonphilips** [comment]
Greatly done @AliReza1083

**Comment by alisamadiii** [comment]
Thanks @Kellsonphilips

**Comment by Kellsonphilips** [comment]
We need to assign the logo to Asakatsu Org already

**Comment by alisamadiii** [comment]
Yeah, we need it.
@Kellsonphilips

**Comment by Kellsonphilips** [comment]
This issue is completed
