### ISSUE TITLE
Set Goal (Divv):[Learn Html and Css]

### ISSUE THREAD

**Issue by DivvSaxena** [asakatsuOrg/AsaKatsuProject#141]
My Goal is to Complete Html and Css by the end of October.
Set your goal and break it into smaller chunks.
 
Learn daily! 
[] complete with W3 School Resource

**Comment by Kellsonphilips** [comment]
You got this @DivvSaxena, I hope to see your daily achievements here when you make a PR.

If you need any help do ask here

**Comment by DivvSaxena** [comment]
Today, was not able to do much but learned more about Html , increased my knowledge due to some other work

**Comment by Kellsonphilips** [comment]
After each day, when you finish your learning. You have to make a PR here and we can record your progress. 

Clone this project repo, go into the report folder, and create a folder that bears your GitHub username. 
Inside the folder, create a file where you will be recording your daily progress, after you register your daily progress then you send a PR to the AsakatsProject repo and we will see it and merge your record with ours. 

That's how you do it. 
hope this helps

**Comment by DivvSaxena** [comment]
Oh Nice @Kellsonphilips  for telling this information!!

**Comment by Kellsonphilips** [comment]
If you are confused about anything. Ask here, I will respond to it as fast as I can. 

With this process, you will learn how use git also.

**Comment by DivvSaxena** [comment]
I am learning HTML and Css from Freecodecamp and  W3 Schools these are my resources any other would u suggest , and Any  tips while learningthese languages it will be helpful to me

**Comment by Kellsonphilips** [comment]
They are fine as far as you are having fun with the tutorial.

**Comment by DivvSaxena** [comment]
#159

**Comment by DivvSaxena** [comment]
@Kellsonphilips  I made the PR of adding a folder and will also add daily updates!
#159

**Comment by Kellsonphilips** [comment]
I will check it. Good job

**Comment by elucian** [comment]
Try my tutorial. Maybe this will help you: This tutorial has no ads and is 100% free.
[Web Design](https://sagecode.net/html)

**Comment by DivvSaxena** [comment]
@elucian  Thanks for Sharing your Resource!

**Comment by DivvSaxena** [comment]
Made the final PR #232 as the goal was for this month and it is completed.

**Comment by Kellsonphilips** [comment]
Well done, you can always start a new task by making a new issue and we can close the last issue.
