### ISSUE TITLE
Set Goal (Niveytha Waran):[2 Leetcode Qns/day]

### ISSUE THREAD

**Issue by Niveytha** [asakatsuOrg/AsaKatsuProject#152]
**What is your goal?**
I want to complete 2 Leetcode Questions per day for the next 30 days.

### Steps to achieve the goal (not required)
  - [ ] 1 Question in the morning on the way to work (weekday), in the morning after showering (weekend)
  - [ ] 1 Question in the evening on the way back home from home /at home (weekday), in the evening before gym (weekend)

**Do you have a target date for this? If yes, write below**
19 November 2022

**What will you achieve by completing this goal?**
Keep my skills and knowledge fresh so I can land a good internship/job. Prep for tehcnical interviews.

**Comment by Niveytha** [comment]
**Additional Context:**
Google Spreadsheet to track progress: https://docs.google.com/spreadsheets/d/1CBrMSh8dE8Hu38TL7_p-LRiK1QR7r79wKAL_sQ1IfjE/edit?usp=sharing

Leetcode List: https://leetcode.com/list/?selectedList=ebpg71ej

**Comment by Kellsonphilips** [comment]
When you fork this repo and created your personal folder inside the report folder, create a file and have your spreadsheet inside the file where you track your daily progress and whenever you update your spreadsheet and your file. Make a PR and we will merge it into your report. 

Hope this helps you start being consistent. Goodluck @Niveytha

**Comment by Niveytha** [comment]
Great idea. Implemented it, thanku!

**Comment by Kellsonphilips** [comment]
Sure, but for now do update your folder in the report folder
