### ISSUE TITLE
Set Goal NateEmerson:Write

### ISSUE THREAD

**Issue by nateemerson** [asakatsuOrg/AsaKatsuProject#19]
**What is your goal?**
Write every day for 30 minutes.

### Steps to achieve the goal (not required)
  - [ ] Write
    - [ ] Daily
      - [ ] For 30 minutes

**Do you have a target date for this? If yes, write below**
2023-01-01

**What will you achieve by completing this goal?**
I will write more

**Additional context**
I want to write more

**Comment by avie-dev** [comment]
@nateemerson Reminder to continue the challenge (Sep21)

**Comment by nateemerson** [comment]
Updated in 1f0e00c31146a5d2bd38e886eba97ad1be065b2e. Already failed on the first day but I'm not stopping! Might have to lower the bar a bit though..30 minutes straight of writing is longer than it sounds!

**Comment by nateemerson** [comment]
Update: 30 minutes is much more difficult than I thought! I might pivot my goals a bit and try for 3x 10min chunks every day so I can gauge my success on a scale of 0-3 pts each day. That way I can adjust my goal to be "15-18 points / week" to allow myself to miss a day or two.

**Comment by alisamadiii** [comment]
Hi @nateemerson 
The target of this goal is `2023/01/01`.
I hope you achieve your goal.
Can we close this issue?

**Comment by nateemerson** [comment]
I did not achieve this goal w/ the initial scope, but I did challenge myself and learn through the process!

**Comment by Kellsonphilips** [comment]
Welldone @nateemerson  
It's okay to start over if that is okay with you.
