### ISSUE TITLE
 Adwait-Dash:Deaddiction

### ISSUE THREAD

**Issue by epicadidash** [asakatsuOrg/AsaKatsuProject#20]
**Not to be addicted to Social Media**
For that only tow hours for social media a day.

### Steps to achieve the goal (not required)
  - [x] Not to use Instagram till 29th September
  - [x]  Not to join more than 1 twitter spaces a day till 29th September.

**Target Date is 29th September 2022**

**Dedicated to algorithm of social media **

**Comment by avie-dev** [comment]
@epicadidash Reminder to continue the challenge (Sep21)

**Comment by alisamadiii** [comment]
Hi @epicadidash 
The target of this goal is 2022/29/09.
I hope you achieve your goal.
Can we close this issue?

**Comment by epicadidash** [comment]
Sure
