### ISSUE TITLE
Set Goal (Avie): 100DaysOf Spaces

### ISSUE THREAD

**Issue by avie-dev** [asakatsuOrg/AsaKatsuProject#223]
**What is your goal?**
Complete 100 days of the Twitter Spaces Challenge
https://twitter.com/AvieDev/status/1574354888926310400?s=20&t=8StCAEoEOGCZul573J46kA

### Steps to achieve the goal
  - [x] Day1
  - [x] Day2
  - [x] Day3
  - [x] Day4
  - [x] Day5
  - [x] Day6
  - [x] Day7
  - [x] Day8
  - [x] Day9
  - [x] Day10
  - [x] Day11
  - [x] Day12
  - [x] Day13
  - [x] Day14
  - [x] Day15
  - [x] Day16
  - [x] Day17
  - [x] Day18
  - [x] Day19
  - [x] Day20
  - [x] Day21
  - [x] Day22
  - [x] Day23
  - [x] Day24
  - [x] Day25
  - [x] Day26
  - [x] Day27
  - [x] Day28
  - [x] Day29
  - [x] Day30
  - [x] Day31
  - [x] Day32
  - [x] Day33
  - [x] Day34
  - [x] Day35
  - [x] Day36
  - [x] Day37
  - [x] Day38
  - [x] Day39
  - [x] Day40
  - [x] Day41
  - [x] Day42
  - [x] Day43
  - [x] Day44
  - [x] Day45
  - [x] Day46
  - [x] Day47
  - [x] Day48
  - [x] Day49
  - [x] Day50
  - [x] Day51
  - [x] Day52
  - [x] Day53
  - [x] Day54
  - [x] Day55
  - [x] Day56
  - [x] Day57
  - [x] Day58
  - [x] Day59
  - [x] Day60
  - [x] Day61
  - [x] Day62
  - [x] Day63
  - [x] Day64
  - [x] Day65
  - [x] Day66
  - [x] Day67
  - [x] Day68
  - [x] Day69
  - [x] Day70
  - [x] Day71
  - [x] Day72
  - [x] Day73
  - [x] Day74
  - [x] Day75
  - [x] Day76
  - [x] Day77
  - [x] Day78
  - [x] Day79
  - [x] Day80
  - [x] Day81
  - [x] Day82
  - [x] Day83
  - [x] Day84
  - [x] Day85
  - [x] Day86
  - [x] Day87
  - [x] Day88
  - [x] Day89
  - [x] Day90
  - [x] Day91
  - [x] Day92
  - [x] Day93
  - [x] Day94
  - [x] Day95
  - [x] Day96
  - [x] Day97
  - [x] Day98
  - [x] Day99
  - [x] Day100
  
**Do you have a target date for this? If yes, write below**
- January 2023

**What will you achieve by completing this goal?**
- Public Speaking Skills
- Conversation Skill
- Deeper connections with people

**Additional context**

**Comment by avie-dev** [comment]
Done!

**Comment by AryaCodesAI** [comment]
Congratulations Avie Chan!!!
