### ISSUE TITLE
Set Goal (Rupali): Revising Javascript

### ISSUE THREAD

**Issue by rupali-codes** [asakatsuOrg/AsaKatsuProject#227]
**What is your goal?**
Set your goal and break it into smaller chunks.
For example, you want to read 4 books in one month. Break it down to “Read one book per week”, or smaller, “Read xx chapter per day”.

Hi, my goal is revise core concepts of JavaScript

### To be learnt
 
  - [x] DataTypes
  - [x] Convential functions Vs Arrow function
  - [x] Array and it's methods
  - [x] Object and it's methods
  - [x] Callback and callstack
  - [x] Scop chain
  - [x] Hoisting
  - [x] let, const & var
  - [x] 'this' keyword
  - [x] Data Structure
  - [x] Closure
  - [x] Promises

**Do you have a target date for this? If yes, write below**
Before this weekend, (Oct 6th, 2022)

**What will you achieve by completing this goal?**
I would learn or revise core concepts of Javascript and will start learning DSA!

**Additional context**

**Comment by Kellsonphilips** [comment]
make a PR if you revised some topic, and write it in a file you created inside the report folder.
 - create a folder bearing your name in the report folder.
 - inside the folder bearing your name, create a file with a name you like or give it a name you can recognize
 - always write what you did every day inside the file and send a PR.
That's it @rupali-codes

**Comment by rupali-codes** [comment]
Thank you @Kellsonphilips :)

**Comment by Kellsonphilips** [comment]
You are welcome @rupali-codes
