### ISSUE TITLE
Moving folders created in the WRONG place!!!! 

### ISSUE THREAD

**Issue by 44jax44** [asakatsuOrg/AsaKatsuProject#32]
It came to my attention, that someone did not read the readme, and someone else, did not check it correctly 

And because of that, now we need to change the location of the folder named [asakatsu_reports/chaaals/Calisthenics... into reports

Thank you

**Comment by avie-dev** [comment]
Hi @44jax44.
Done with this. Please check and close the issue, thanks

**Comment by 44jax44** [comment]
Thank you
