### ISSUE TITLE
Set Goal Elucian: Learn Bash

### ISSUE THREAD

**Issue by elucian** [asakatsuOrg/AsaKatsuProject#4]
**Learn Bash in 15 days**

### Steps
  - [x] Read the reference manual
  - [x] Create Train repository
  - [x] Create code snippets
  - [x] Create articles
  - [x] Create quiz
  - [x] Create slides
  - [x] Stream on Twitch

**Target Date**

Saturday: 1 Oct 2022

**Purpose**

This is part of my training to become: #10xEngineer. It require a software developer to know at least 10 programming languages. Has nothing to do with productivity LOL

**Comment by avie-dev** [comment]
@elucian Reminder For Sep21🌷

**Comment by elucian** [comment]
I'm on it. 2 goals remaining!

**Comment by elucian** [comment]
I have finish learning Bash fundamental concepts and stream my first tutorial.
