### ISSUE TITLE
Set Goal chaaals: Get into Calisthenics and Boxing 👟🥊

### ISSUE THREAD

**Issue by chaaals** [asakatsuOrg/AsaKatsuProject#6]
**What is your goal?**
Generally, its to lose weight around min(5kg), max(7.5kg) by getting into Calisthenics and Boxing

**Do you have a target date for this? If yes, write below**
I want to achieve it in 1 month with a proper morning routine.

**What will you achieve by completing this goal?**
Planning out a training routine that I can do for 4-5 days a week.

**Additional context**
I've always been interested in Calisthenics and Boxing, but I've never been committed into doing it! Hopefully this will help me push myself a bit :>. After a month of getting into it, I think I'll be at a state where I am motivated and in shape on doing my former routine.

**Comment by avie-dev** [comment]
@chaaals I don't see the second day ;)

**Comment by Kellsonphilips** [comment]
Seems Chaaals dropped off the task

**Comment by Kellsonphilips** [comment]
I thought same
