### ISSUE TITLE
How to add tag

### ISSUE THREAD

**Issue by ghost** [asakatsuOrg/AsaKatsuProject#60]
Hi @avie-dev !! 
could you tell how to add tags to a pr ?

**Comment by avie-dev** [comment]
hi @ayushdotdev, apologies I missed this question.
You can put labels on them. Go to the PR, on the left side there is a Labels option, choose from there or create one.

**Comment by ghost** [comment]
Thank you @avie-dev .😀🌻  Its okay I can understand your side situation maintainers do many things .😁
Thanks man @Kellsonphilips for assigning it to me .😁😊
I am not currently practicing AsaKatsu, I will be back soon . Its really good intiative 😁✌🏻
