### ISSUE TITLE
Set Goal (Elucian):[Translate up to 5000 words]

### ISSUE THREAD

**Issue by elucian** [asakatsuOrg/AsaKatsuProject#81]
**What is your goal?**
Translate 5000 words in Maj and other 6 languages until the end of 2020: 
Target languages: {Romanian, English, Spanish, French, Italian, German}

### Steps to achieve the goal (not required)
  - [x] Fix existing duplicates (10) until Oct 09 
  - [x] Update GitHub repository until Oct 09 - 2022
  - [x] Fix website broken links until Oct 16 - 2022
  - [x] Translate 5000 words until Oct 24 - 2022
 
**What will you achieve by completing this goal?**

By finishing Maj lexicon we open road to a new communication tool. Next year we can focus on expressions, grammar improvements and Maj chat. Website will be update next year. 

**Additional context**

Project is open source: [visit maj](https://github.com/sage-code/maj)

**Comment by elucian** [comment]
Work is progressing well, I have made my second PR today

**Comment by alisamadiii** [comment]
Nice @elucian 
You're doing great
Keep going

**Comment by elucian** [comment]
I have finished 5050 words. Though I have discovered duplicates.

**Comment by elucian** [comment]
I have check-in the report for today. My goal is on target. All duplicates are eliminates and 5000 words are good to go. Working on extra bunch of 200 word to clear from my queue.

**Comment by elucian** [comment]
All done. 5072 words are available in Maj lexicon. Broken links are fixed.
Project is in Beta stage. Left to do: Update the website with new examples.

**Comment by elucian** [comment]
I try to change the label to done but I can't
